apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.freenasConfig.secretName }}
  labels:
{{ include "freenas-provisioner.labels" . | nindent 4 }}
type: Opaque
stringData:
  protocol: "{{ .Values.freenasConfig.protocol }}"
  host: "{{ .Values.freenasConfig.host }}"
  port: "{{ .Values.freenasConfig.port }}"
  username: "{{ .Values.freenasConfig.username }}"
  password: "{{ .Values.freenasConfig.password }}"
  allowInsecure: "{{ .Values.freenasConfig.allowInsecure }}"
