{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "freenas-provisioner.serviceAccountName" . }}
  labels:
{{ include "freenas-provisioner.labels" . | nindent 4 }}
{{- end -}}
